### ISSUE TITLE
Mute switch using keyboard button

### ISSUE THREAD

**Issue by Zipdox** [jonaseberle/novationLaunchControl-jackProxy#1]
Could you make simple JACK proxy program to listen for a key press on a specified key to toggle mute?

**Comment by jonaseberle** [comment]
Hi @Zipdox, 
what do you want to mute?

**Comment by Zipdox** [comment]
The proxy. Just a simple jack proxy that toggles mute when a button is pressed.

**Comment by jonaseberle** [comment]
Sorry, you would need to put some more effort in describing your use case.
